# Generated by Django 2.2.9 on 2020-03-10 04:43

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_body', models.TextField()),
                ('notification_datetime', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
            ],
            options={
                'default_related_name': 'General Notifications',
            },
        ),
        migrations.CreateModel(
            name='StockTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_tip_datetime', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('type', models.CharField(choices=[('free', 'free'), ('premium', 'premium')], default='free', max_length=7)),
                ('category', models.CharField(choices=[('Short term', 'Short term'), ('Long term', 'Long term'), ('Intraday', 'Intraday'), ('Commodity', 'Commodity')], default='intraday', max_length=10)),
                ('description', models.TextField()),
                ('note', models.TextField()),
                ('note_datetime', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
            ],
            options={
                'default_related_name': 'Stock Tips',
            },
        ),
    ]
