# Generated by Django 2.1.9 on 2020-04-14 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktip',
            options={'verbose_name': 'Stock Tip', 'verbose_name_plural': 'Stock Tips'},
        ),
        migrations.AddField(
            model_name='stocktip',
            name='target_achieved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stocktip',
            name='target_achieved_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 15, 29, 33, 669746)),
        ),
    ]
