# Generated by Django 2.1.9 on 2020-04-14 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapi', '0002_auto_20200414_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktip',
            name='target_achieved_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 16, 42, 24, 886544)),
        ),
    ]
