# Generated by Django 2.1.9 on 2020-04-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapi', '0004_auto_20200414_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktip',
            name='note_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stocktip',
            name='target_achieved_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
