# Generated by Django 2.1.9 on 2020-05-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapi', '0006_auto_20200420_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktip',
            name='category',
            field=models.CharField(choices=[('Short term', 'Short term'), ('Long term', 'Long term'), ('Intraday', 'Intraday'), ('Commodity', 'Commodity')], default='Intraday', max_length=10),
        ),
    ]
