# Generated by Django 2.1.9 on 2020-05-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapi', '0008_auto_20200516_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktip',
            name='category',
            field=models.CharField(choices=[('Short Term (Intraday Cash)', 'Short Term (Intraday Cash)'), ('Intraday (Intraday Future)', 'Intraday (Intraday Future)'), ('Hero or Zero (Intraday Option)', 'Hero or Zero (Intraday Option)'), ('Long Term (Positional Cash)', 'Long Term (Positional Cash)'), ('Commodity & Currency', 'Commodity & Currency')], default='Short Term (Intraday Cash)', max_length=133),
        ),
    ]
