# Generated by Django 2.1.9 on 2020-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapi', '0009_auto_20200517_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktip',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
