# Generated by Django 3.2.7 on 2021-10-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapi', '0010_auto_20200523_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
