# Generated by Django 3.2.7 on 2021-10-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapi', '0011_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericnotification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='genericnotification',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.RemoveField(
            model_name='stocktip',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stocktip',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='GenericNotification',
        ),
        migrations.DeleteModel(
            name='StockTip',
        ),
    ]
