# Generated by Django 3.2.7 on 2021-10-11 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomSellerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('image', models.ImageField(upload_to='seller_slider_img')),
                ('category', models.CharField(default='#', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CenterSellerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('image', models.ImageField(upload_to='seller_slider_img')),
                ('category', models.CharField(default='#', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=50)),
                ('root_category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('price_not', models.PositiveIntegerField(default=999)),
                ('desc', models.TextField()),
                ('gst', models.CharField(choices=[('0', '0'), ('3', '3'), ('5', '5'), ('12', '12'), ('18', '18'), ('28', '28')], default='0', max_length=3)),
                ('pub_date', models.DateField(auto_now=True)),
                ('aproved_product', models.BooleanField(default=False, max_length=5)),
                ('product_zipcode', models.CharField(max_length=10)),
                ('out_of_stock', models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', help_text='True this field to Show Product is Out Of Stock', max_length=6)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('image1', models.ImageField(default='', upload_to='products/images')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='products/images')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='products/images')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='products/images')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='products/images')),
                ('shop', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopSellerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('image', models.ImageField(upload_to='seller_slider_img')),
                ('category', models.CharField(default='#', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingProduct',
            fields=[
                ('tranding_product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('out_of_stock', models.BooleanField(choices=[(False, False), (True, True)], default=False, help_text='True this field to Show Product is Out Of Stock', max_length=6)),
                ('product', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='seller_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('root_category', models.CharField(default='', max_length=25)),
                ('sub_categories', models.TextField(default='', help_text="add multiple items seprated by ','commas")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='seller_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='SellerCart',
            fields=[
                ('seller_cart_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('product_size_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('colour', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsize', to='seller_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('product_review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('product_rating', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_api.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=50)),
                ('saler', models.CharField(default='wrappers@admin', max_length=100)),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=220)),
                ('price', models.CharField(max_length=50)),
                ('product_cat_subcat', models.CharField(max_length=220, null=True)),
                ('size', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Cancel', 'Cancel')], default='', max_length=15)),
                ('deliver_boy_number', models.CharField(max_length=15, null=True)),
                ('order_date_time', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('Online', 'Online'), ('CashOnDelivery', 'CashOnDelivery')], default='CashOnDelivery', max_length=15)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
