# Generated by Django 3.2.7 on 2021-10-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_api', '0002_alter_productreview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size',
        ),
        migrations.CreateModel(
            name='ProductSize_and_quantity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_api.product')),
                ('productsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsize_and_quantity', to='seller_api.productsize')),
            ],
        ),
    ]
