# Generated by Django 3.2.7 on 2021-10-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_api', '0004_remove_productsize_and_quantity_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize_and_quantity',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller_api.product'),
            preserve_default=False,
        ),
    ]
