# Generated by Django 2.1.9 on 2020-03-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_trial_period_popup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trial_period_days',
            field=models.CharField(default='30', max_length=5),
        ),
    ]
