# Generated by Django 2.1.9 on 2020-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0003_auto_20200414_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='belongs_to',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
