# Generated by Django 2.1.9 on 2020-05-05 12:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0004_userprofile_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ST', 'Short Term'), ('LT', 'Long Term'), ('ID', 'Intraday'), ('CD', 'Commodity')], max_length=20, null=True),
        ),
    ]
