# Generated by Django 2.1.9 on 2020-05-05 12:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0005_auto_20200505_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ST', 'Short Term'), ('LT', 'Long Term'), ('ID', 'Intraday'), ('CD', 'Commodity')], default=('ST', 'LT', 'ID', 'CD'), max_length=20),
        ),
    ]
