# Generated by Django 2.1.9 on 2020-05-16 18:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0009_auto_20200505_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Short Term (Intraday Cash)', 'Short Term (Intraday Cash)'), ('Intraday (Intraday Future)', 'Intraday (Intraday Future)'), ('Hero or Zero (Intraday Option)', 'Hero or Zero (Intraday Option)'), ('Long Term (Positional Cash)', '(Positional Cash)'), ('Commodity & Currency', 'Commodity & Currency')], default=('Short Term (Intraday Cash)', 'Intraday (Intraday Future)', 'Hero or Zero (Intraday Option)', 'Long Term (Positional Cash)', 'Commodity & Currency'), max_length=133),
        ),
    ]
