# Generated by Django 2.1.9 on 2020-05-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0014_auto_20200523_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='in_app_price_display',
            field=models.IntegerField(blank=True, help_text='Please put only digits', null=True),
        ),
    ]
