# Generated by Django 2.1.9 on 2020-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0015_auto_20200528_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='change_price_for_all',
            field=models.BooleanField(default=False, help_text='Check this field if you want to change the price for all the app users, else keep unchecked to change the price just for this user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='no_trial_period_popup',
            field=models.BooleanField(default=False, help_text='Check this field to remove popup blocker for this user'),
        ),
    ]
