# Generated by Django 2.1.9 on 2020-05-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0017_remove_userprofile_change_price_for_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_pricing', models.IntegerField()),
            ],
            options={
                'verbose_name': 'App Pricing',
                'verbose_name_plural': 'App Pricing',
            },
        ),
    ]
