# Generated by Django 2.1.9 on 2021-03-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0019_auto_20200528_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='no_trial_period_popup',
            new_name='no_subscription_popup',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribe',
            field=models.BooleanField(default=False, help_text='Check this field to add Premium stock tips for this user'),
        ),
    ]
