# Generated by Django 3.2.7 on 2021-10-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0020_auto_20210317_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppPricing',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
