# Generated by Django 3.2.7 on 2021-10-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0026_user_is_delivery_boy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryboyprofile',
            old_name='mobile',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='sallerdetail',
            old_name='mobile',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobile',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='customer_id',
        ),
    ]
