# Generated by Django 3.2.7 on 2021-10-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0027_auto_20211003_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboyprofile',
            name='customer_id',
        ),
    ]
