# Generated by Django 3.2.7 on 2021-10-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0029_alter_deliveryboyprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='adharcard',
            field=models.ImageField(upload_to='delivery_boy_adharcard'),
        ),
    ]
