# Generated by Django 3.2.7 on 2021-10-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0030_alter_deliveryboyprofile_adharcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='adharcard',
            field=models.ImageField(default='default.png', upload_to='delivery_boy_adharcard'),
        ),
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='delivery_boy_photos'),
        ),
    ]
