# Generated by Django 3.2.7 on 2021-10-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0032_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='address',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(),
        ),
    ]
