# Generated by Django 3.2.7 on 2021-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0033_auto_20211003_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='photo',
            field=models.ImageField(upload_to='delivery_boy_photos'),
        ),
    ]
