# Generated by Django 3.2.7 on 2021-10-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0034_auto_20211003_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='address',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='delivery_boy_photos'),
        ),
    ]
