# Generated by Django 3.2.7 on 2021-10-04 14:48

from django.db import migrations, models
import users_auth_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0036_auto_20211004_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='adharcard',
            field=models.ImageField(null=True, upload_to='delivery_boy_adharcard'),
        ),
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to='delivery_boy_photos'),
        ),
        migrations.AlterField(
            model_name='sallerdetail',
            name='adharcard',
            field=models.ImageField(null=True, upload_to=users_auth_api.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='sallerdetail',
            name='gumasta',
            field=models.ImageField(null=True, upload_to=users_auth_api.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='sallerdetail',
            name='pancard',
            field=models.ImageField(null=True, upload_to=users_auth_api.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='sallerdetail',
            name='photo',
            field=models.ImageField(null=True, upload_to=users_auth_api.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='sallerdetail',
            name='shop_Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_photos'),
        ),
    ]
