# Generated by Django 3.2.7 on 2021-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0038_auto_20211004_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sallerdetail',
            name='aproved_user',
            field=models.BooleanField(default=False, max_length=6),
        ),
    ]
